# Generated by Django 5.2.5 on 2025-09-05 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tariff', '0003_entry_entered_value_entry_gross_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HTSUSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('uom', models.CharField(blank=True, help_text='Unit of measure', max_length=20)),
                ('rate_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Simple ad valorem rate % for quick calculations', max_digits=7, null=True)),
                ('has_complex_rates', models.BooleanField(default=False, help_text='If True, check HTSRateDetail for country/program specific rates')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_file_name', models.CharField(max_length=255)),
                ('total_items', models.IntegerField(default=0)),
                ('total_vendor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_additional_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculation_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calculation History',
                'verbose_name_plural': 'Calculation Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('vendor_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('htsus_code', models.CharField(blank=True, max_length=20)),
                ('tariff_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customs_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_costs', models.JSONField(blank=True, default=dict)),
                ('total_additional_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='cogs.calculationhistory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HTSRateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('trade_program', models.CharField(blank=True, help_text='SPI code', max_length=10)),
                ('rate_type', models.CharField(choices=[('ADVAL', 'Ad Valorem (%)'), ('SPECIFIC', 'Specific (per unit)'), ('COMPOUND', 'Compound (both)')], default='ADVAL', max_length=10)),
                ('adval_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('specific_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('specific_uom', models.CharField(blank=True, max_length=20)),
                ('additional_duty_type', models.CharField(blank=True, max_length=20)),
                ('additional_duty_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('hts_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_details', to='cogs.htsuscode')),
            ],
            options={
                'ordering': ['country_code', 'trade_program', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('country_origin', models.CharField(blank=True, help_text='Country of manufacture (ISO 2-letter code) for all items in this invoice', max_length=2, null=True)),
                ('po_number', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('apply_db_htsus_rate', models.BooleanField(default=True, help_text='If False, manual HTSUS rate will be used for this invoice.')),
                ('manual_htsus_rate_pct', models.DecimalField(blank=True, decimal_places=2, help_text="Manual HTSUS rate for this invoice (e.g. 3.5 for 3.5%). Used if 'Apply DB HTSUS Rate' is False.", max_digits=5, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogs.container')),
                ('entry', models.ForeignKey(blank=True, help_text='Link to customs entry if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariff.entry')),
            ],
        ),
        migrations.CreateModel(
            name='CostPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('INVOICE', 'Invoice'), ('CONTAINER', 'Container'), ('ALL', 'All')], max_length=10)),
                ('method', models.CharField(choices=[('PRICE', 'Price'), ('VOLUME', 'Volume'), ('QUANTITY', 'Quantity'), ('EQUALLY', 'Equally'), ('PRICE_QUANTITY', 'Price * Quantity')], max_length=20)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto_compute', models.BooleanField(default=False, help_text='True for system pools like HTSUS tariff')),
                ('shipment_company', models.CharField(blank=True, max_length=200, null=True)),
                ('shipment_invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cogs.container')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cogs.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_vendor', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('total_vendor', models.DecimalField(decimal_places=2, help_text='Denormalized from CSV for validation', max_digits=10)),
                ('unit_volume_cc', models.FloatField(help_text='Volume per unit in cubic centimeters')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cogs.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cogs.costpool')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cogs.invoiceline')),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('htsus_rate_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Overrides HTSUSCode rate if present', max_digits=7, null=True)),
                ('origin_country', models.CharField(blank=True, help_text='ISO 2-letter country code', max_length=2, null=True)),
                ('claimed_spi', models.CharField(blank=True, help_text='Special Program Indicator', max_length=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True, help_text='Reason for rate override')),
                ('htsus_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogs.htsuscode')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cogs.sku'),
        ),
    ]
