# Generated by Django 5.2.5 on 2025-08-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HSUSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('rate_pct', models.DecimalField(decimal_places=2, help_text='e.g. 3.5 means 3.5%', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('po_number', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogs.container')),
            ],
        ),
        migrations.CreateModel(
            name='CostPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('INVOICE', 'Invoice'), ('CONTAINER', 'Container')], max_length=10)),
                ('method', models.CharField(choices=[('PRICE', 'Price'), ('VOLUME', 'Volume'), ('QUANTITY', 'Quantity')], max_length=10)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto_compute', models.BooleanField(default=False, help_text='True for system pools like HSUS tariff')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cogs.container')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cogs.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_vendor', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('total_vendor', models.DecimalField(decimal_places=2, help_text='Denormalized from CSV for validation', max_digits=10)),
                ('unit_volume_cc', models.FloatField(help_text='Volume per unit in cubic centimeters')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cogs.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cogs.costpool')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cogs.invoiceline')),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('hsus_rate_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides HSUSCode rate if present', max_digits=5, null=True)),
                ('hsus_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cogs.hsuscode')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cogs.sku'),
        ),
    ]
