# Generated by Django 5.2.5 on 2025-08-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='apply_db_hsus_rate',
            field=models.BooleanField(default=True, help_text='If False, manual HSUS rate will be used for this invoice.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='manual_hsus_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Manual HSUS rate for this invoice (e.g. 3.5 for 3.5%). Used if 'Apply DB HSUS Rate' is False.", max_digits=5, null=True),
        ),
    ]
