# Generated by Django 5.2.5 on 2025-08-28 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0002_invoice_apply_db_hsus_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_file_name', models.CharField(max_length=255)),
                ('total_items', models.IntegerField(default=0)),
                ('total_vendor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_additional_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculation_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calculation History',
                'verbose_name_plural': 'Calculation Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('vendor_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('hsus_code', models.CharField(blank=True, max_length=20)),
                ('tariff_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customs_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_costs', models.JSONField(blank=True, default=dict)),
                ('total_additional_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='cogs.calculationhistory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
