# Generated by Django 5.2.5 on 2025-08-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0002_add_apply_db_htsus_rate_field'),
    ]

    operations = [
    ]
