# Generated by Django 5.2.5 on 2025-08-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0003_calculationhistory_calculationlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='costpool',
            name='shipment_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='costpool',
            name='shipment_invoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
