# Generated by Django 5.2.5 on 2025-09-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0004_add_htsus_code_to_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='claimed_spi',
            field=models.CharField(blank=True, help_text='Special Program Indicator', max_length=10),
        ),
        migrations.AddField(
            model_name='sku',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='origin_country',
            field=models.CharField(blank=True, help_text='ISO 2-letter country code', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='override_reason',
            field=models.TextField(blank=True, help_text='Reason for rate override'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='htsus_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Overrides HTSUSCode rate if present', max_digits=7, null=True),
        ),
    ]
