# Generated by Django 5.2.5 on 2025-08-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0004_costpool_shipment_company_costpool_shipment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costpool',
            name='method',
            field=models.CharField(choices=[('PRICE', 'Price'), ('VOLUME', 'Volume'), ('QUANTITY', 'Quantity'), ('EQUALLY', 'Equally')], max_length=10),
        ),
        migrations.AlterField(
            model_name='costpool',
            name='scope',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('CONTAINER', 'Container'), ('ALL', 'All')], max_length=10),
        ),
    ]
