# Generated by Django 5.2.5 on 2025-09-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0005_unified_sku_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='htsuscode',
            name='has_complex_rates',
            field=models.BooleanField(default=False, help_text='If True, check HTSRateDetail for country/program specific rates'),
        ),
        migrations.AddField(
            model_name='htsuscode',
            name='uom',
            field=models.CharField(blank=True, help_text='Unit of measure', max_length=20),
        ),
        migrations.AlterField(
            model_name='htsuscode',
            name='rate_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Simple ad valorem rate % for quick calculations', max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='HTSRateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('trade_program', models.CharField(blank=True, help_text='SPI code', max_length=10)),
                ('rate_type', models.CharField(choices=[('ADVAL', 'Ad Valorem (%)'), ('SPECIFIC', 'Specific (per unit)'), ('COMPOUND', 'Compound (both)')], default='ADVAL', max_length=10)),
                ('adval_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('specific_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('specific_uom', models.CharField(blank=True, max_length=20)),
                ('additional_duty_type', models.CharField(blank=True, max_length=20)),
                ('additional_duty_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('hts_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_details', to='cogs.htsuscode')),
            ],
            options={
                'ordering': ['country_code', 'trade_program', '-effective_from'],
            },
        ),
    ]
