# Generated by Django 5.2.5 on 2025-08-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0005_alter_costpool_method_alter_costpool_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costpool',
            name='method',
            field=models.CharField(choices=[('PRICE', 'Price'), ('VOLUME', 'Volume'), ('QUANTITY', 'Quantity'), ('EQUALLY', 'Equally'), ('PRICE_QUANTITY', 'Price * Quantity')], max_length=20),
        ),
    ]
