# Generated by Django 5.2.5 on 2025-09-02 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0006_unified_hts_model'),
        ('tariff', '0003_entry_entered_value_entry_gross_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='entry',
            field=models.ForeignKey(blank=True, help_text='Link to customs entry if available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariff.entry'),
        ),
    ]
