# Generated by Django 5.2.5 on 2025-09-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogs', '0007_add_entry_to_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='country_origin',
            field=models.CharField(blank=True, help_text='Country of manufacture (ISO 2-letter code) for all items in this invoice', max_length=2, null=True),
        ),
    ]
