# Generated by Django 5.2.5 on 2025-08-26 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField()),
                ('ptd_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_pnl', models.BooleanField(default=True)),
                ('chart_of_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consolidation_app.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consolidation_app.company')),
            ],
            options={
                'unique_together': {('company', 'chart_of_account', 'period_date', 'is_pnl')},
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('financial_data_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consolidation_app.financialdata')),
            ],
        ),
    ]
