# Generated by Django 5.2.5 on 2025-08-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidation_app', '0002_financialdata_supportingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='llm_suggested_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='llm_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
