# Generated by Django 5.2.5 on 2025-08-26 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidation_app', '0003_chartofaccount_llm_suggested_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allocation_type', models.CharField(choices=[('revenue', 'Revenue-based'), ('headcount', 'Headcount-based'), ('custom', 'Custom Ratio')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consolidation_app.company')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_for_allocations', to='consolidation_app.chartofaccount')),
                ('target_accounts', models.ManyToManyField(related_name='target_for_allocations', to='consolidation_app.chartofaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consolidation_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consolidation_app.company')),
            ],
            options={
                'unique_together': {('name', 'company', 'period_start_date', 'period_end_date')},
            },
        ),
    ]
