# Generated by Django 5.2.5 on 2025-08-26 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidation_app', '0004_allocationrule_project_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consolidation_app.project'),
        ),
    ]
