# Generated by Django 5.2.5 on 2025-08-26 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consolidation_app', '0005_financialdata_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField()),
                ('budget_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consolidation_app.budget')),
                ('chart_of_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consolidation_app.chartofaccount')),
            ],
            options={
                'unique_together': {('budget', 'chart_of_account', 'period_date')},
            },
        ),
    ]
