# Generated by Django 5.2.5 on 2025-08-29 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=32, unique=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('import_date', models.DateField()),
                ('mode', models.CharField(max_length=10)),
                ('port_of_entry', models.CharField(blank=True, max_length=10)),
                ('importer_name', models.CharField(blank=True, max_length=128)),
                ('country_origin', models.CharField(max_length=2)),
                ('country_export', models.CharField(blank=True, max_length=2)),
                ('claimed_spi', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HTSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('description', models.TextField()),
                ('uom', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SkuHtsMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('hts_code', models.CharField(max_length=12)),
                ('origin_country', models.CharField(max_length=2)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('claimed_spi', models.CharField(blank=True, max_length=10)),
                ('rate_override_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('override_reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('mpf_pct', models.DecimalField(decimal_places=6, max_digits=7)),
                ('mpf_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpf_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hmf_pct', models.DecimalField(decimal_places=6, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='TradeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('note_ref', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField()),
                ('hts_code', models.CharField(max_length=12)),
                ('description', models.TextField(blank=True)),
                ('entered_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('hts_rate', models.CharField(blank=True, max_length=16)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.entry')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('rate_type', models.CharField(choices=[('adval', 'Ad Valorem'), ('spec', 'Specific'), ('compound', 'Compound')], max_length=10)),
                ('adval_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('specific_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('specific_uom', models.CharField(blank=True, max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.country')),
                ('hts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.htscode')),
            ],
        ),
        migrations.CreateModel(
            name='ADCVDCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50)),
                ('cash_deposit_rate_pct', models.DecimalField(decimal_places=4, max_digits=7)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.country')),
                ('hts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.htscode')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=32)),
                ('sku', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('uom', models.CharField(default='unit', max_length=16)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('country_origin', models.CharField(blank=True, max_length=2)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.entry')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceToEntryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_mapped', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('value_mapped', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('entry_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.entryline')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.invoiceline')),
            ],
        ),
        migrations.CreateModel(
            name='TariffRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(default='1-General', max_length=8)),
                ('rate_type', models.CharField(choices=[('adval', 'Ad Valorem'), ('spec', 'Specific'), ('compound', 'Compound')], max_length=10)),
                ('adval_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('specific_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('specific_uom', models.CharField(blank=True, max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tariff.country')),
                ('hts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.htscode')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariff.tradeprogram')),
            ],
        ),
    ]
