# Generated by Django 5.2.5 on 2025-08-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_alter_country_options_rename_iso2_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entered_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
