# Generated by Django 5.2.5 on 2025-09-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0003_entry_entered_value_entry_gross_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='section_301_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Section 301 duty rate percentage (e.g., 7.5 for 7.5%)', max_digits=5),
        ),
    ]
